### ISSUE TITLE
Dynamic Imports, Stage 4 Entrance Criteria testing

### ISSUE THREAD

**Issue by rwaldron** [tc39/test262#1567] opened 2018-05-22 19:00 UTC
Dynamic Imports are at Stage 3, with implementations in V8 and JSC (maybe others, but I've only looked at these so far). I plan to first migrate tests from both engines, determine coverage gaps and then fill them.

**Comment by leobalter** [comment] 2018-10-04 20:07
duplicate of #1164

**Closed by leobalter** 2018-10-04 20:07 UTC
