### ISSUE TITLE
Are there sufficient scoping tests?

### ISSUE THREAD

**Issue by littledan** [tc39/test262#503] opened 2016-02-12 18:04 UTC
V8 gets away on test262 with a few things that it probably shouldn't, for example:
- A with statement permits both a function declaration as its body (not in the spec, but I supported it because we have some tests which fail otherwise)
- A for loop permits a function declaration as its body, in both strict and sloppy mode (spec has neither)
- An if statement with a function declaration as its body is permitted in strict mode (should only be in sloppy mode) and when it does happen, I'm not sure if there's the right semantics of it being overwritten (as described in Annex B 3.4)
- We implement the web compatibility workaround that permits `{ function f() {} function f() {} }`, but in the spec, this should be a SyntaxError from the duplicate let declaration. Until the spec is changed, there should in theory be a test262 test prohibiting it.

(Sorry, I haven't double-checked all of these, but I don't see any function declaration related tests that we have marked as known-failing.)

**Comment by jugglinmike** [comment] 2016-03-12 00:20
I can confirm that there is currently no coverage for the details you have identified.

I started work on Annex B.3.4 earlier this week. It turns out that extension is dependent on section 3.3, so the effort ballooned a bit. Because the semantics apply to 7 grammar productions (Block, CaseClause, DefaultClause, and four variants of IfStatement), I wrote them using [the proposed test generation tool](https://github.com/tc39/test262/pull/481). I'm holding off on submitting those tests until the tool is accepted, but you can review my work on [the `dev-gen-annex-b-fns` branch of Bocoup's fork of the repository](https://github.com/jugglinmike/test262/compare/dev-gen...bocoup:dev-gen-annexb-fns).

If the generation tool changes prior to acceptance into `master`, I will update the tests accordingly and submit. If the tool is rejected, then I will file a pull request with the generated files.

The negative syntax tests for "declarations in statement positions" are varied enough (and contained enough) to be maintained as "static" files, without any tooling. I've split that work out into a separate patch and submitted as gh-541.

**Comment by leobalter** [comment] 2017-03-13 20:39
ping @littledan @jugglinmike what is the status on this?

I know we've a good progress on many of the topics you mentioned, but if you can tell what is still missing here, this would save me a precious time.

**Comment by jugglinmike** [comment] 2017-03-19 16:07
The pull request I referenced above, gh-541, has since been merged. In addition, the test generation tool was accepted, so I followed through with the plan for Annex B.3.3 and Annex B.3.4: gh-587 . That's also been merged.

I believe these two patches resolve the issue, but since @littledan originally requested this work, I'd like to get his confirmation before closing this issue.

**Closed** 2020-02-07 19:20 UTC
