### ISSUE TITLE
Some recent generated destructuring assignment tests are invalid

### ISSUE THREAD

**Issue by littledan** [tc39/test262#1058] opened 2017-06-08 12:40 UTC
For example, [language/statements/for-await-of/dstr-array-elem-trlg-iter-rest-rtrn-close-null.js](https://github.com/tc39/test262/blob/master/test/language/statements/for-await-of/dstr-array-elem-trlg-iter-rest-rtrn-close-null.js) generates a use of `yield` inside an async function (not an async generator), which is enclosed by a generator. The intervening function makes `yield` simply a token which is banned strict mode. That's the outcome when running in V8.

I don't know of a general fix for this beyond refraining from using for-await-of with the destructuring assignment templates, and writing a new template set, or tagging specific templates for skipping here (which would take some changes to the test template infrastructure).

Assigning to @rwaldron as he wrote this test.

**Comment by rwaldron** [comment] 2017-06-12 20:44
Thanks, this is a duplicate of #1050

**Comment by rwaldron** [comment] 2017-06-12 20:47
Sorry, I closed this prematurely. Just ignore that. 

> For example, language/statements/for-await-of/dstr-array-elem-trlg-iter-rest-rtrn-close-null.js generates a use of yield inside an async function (not an async generator), which is enclosed by a generator. The intervening function makes yield simply a token which is banned strict mode. That's the outcome when running in V8.


I _think_ this test should've had a different template dir? I'll look more closely tomorrow.

**Comment by leobalter** [comment] 2017-06-12 22:52
I believe #1061 reflects a partial work for this issue, mentioning it here for reference

**Comment by rwaldron** [comment] 2017-06-20 17:41
This was addressed

**Closed by rwaldron** 2017-06-20 17:41 UTC
Labels: test bug

**Comment by littledan** [comment] 2017-06-21 10:29
Thanks for the fix!
