### ISSUE TITLE
Can't find propertyHelper.js

### ISSUE THREAD

**Issue by evilpie** [tc39/test262#295] opened 2015-06-03 11:38 UTC
I just ran test262 with the SpiderMonkey shell, however during the run I get the following error:
`Error: Can't find: /home/tom/projects/test262/harness/propertyHelper.js`
However manually looking up this path the file exists.

**Comment by bterlson** [comment] 2015-06-03 15:09
Strange... can you give me the exact harness invocation you're using? Also are you Mac or Linux?

**Comment by evilpie** [comment] 2015-06-03 22:02
`tools/packaging/test262.py --command ~/projects/mozilla-inbound/js/src/debug-obj/dist/bin/js --summary`

on Linux

**Comment by bterlson** [comment] 2015-06-03 22:33
You could try http://github.com/bterlson/test262-harness. Otherwise, I'm not sure how the python harness works. Hopefully someone else can help...

**Comment by anba** [comment] 2015-06-03 22:39
```bash
~/git/test262$ tools/packaging/test262.py --command ~/lib/mozjs --summary "built-ins/Object/defineProperty" > /tmp/moz.txt
```
works for me (Ubuntu 15.04, Python 2.7.9). Can you provide an error stack trace?

**Comment by evilpie** [comment] 2015-06-09 21:59
`(Pdb) l
 35  	class Test262Error(Exception):
 36  	  def __init__(self, message):
 37  	    self.message = message
 38  	
 39  	def ReportError(s):
 40  ->	  raise Test262Error(s)
 41  	
 42  	
 43  	
 44  	if not os.path.exists(EXCLUDED_FILENAME):
 45  	    print "Cannot generate (JSON) test262 tests without a file," + \
(Pdb) up
> /home/tom/projects/test262/tools/packaging/test262.py(441)GetInclude()
-> ReportError("Can't find: " + static)
(Pdb) list
436  	        contents = stripHeader(f.read())
437  	        contents = re.sub(r'\r\n', '\n', contents)
438  	        self.include_cache[name] = contents + "\n"
439  	        f.close()
440  	      else:
441  ->	        ReportError("Can't find: " + static)
442  	    return self.include_cache[name]
443  	
444  	  def EnumerateTests(self, tests):
445  	    logging.info("Listing tests in %s", self.test_root)
446  	    cases = []
(Pdb) bt
  /usr/lib/python2.7/pdb.py(1314)main()
-> pdb._runscript(mainpyfile)
  /usr/lib/python2.7/pdb.py(1233)_runscript()
-> self.run(statement)
  /usr/lib/python2.7/bdb.py(400)run()
-> exec cmd in globals, locals
  <string>(1)<module>()
  /home/tom/projects/test262/tools/packaging/test262.py(11)<module>()
-> import logging
  /home/tom/projects/test262/tools/packaging/test262.py(627)Main()
-> options.junitname)
  /home/tom/projects/test262/tools/packaging/test262.py(545)Run()
-> result = case.Run(command_template)
  /home/tom/projects/test262/tools/packaging/test262.py(361)Run()
-> result = self.RunTestIn(command_template, tmp)
  /home/tom/projects/test262/tools/packaging/test262.py(350)RunTestIn()
-> tmp.Write(self.GetSource(command_template))
  /home/tom/projects/test262/tools/packaging/test262.py(310)GetSource()
-> self.WrapTest(command_template) + '\n'
  /home/tom/projects/test262/tools/packaging/test262.py(283)GetAdditionalIncludes()
-> return '\n'.join([self.suite.GetInclude(include) for include in self.GetIncludeList()])
> /home/tom/projects/test262/tools/packaging/test262.py(441)GetInclude()
-> ReportError("Can't find: " + static)
  /home/tom/projects/test262/tools/packaging/test262.py(40)ReportError()
-> raise Test262Error(s)
(Pdb) self.getIncludeList()
*** AttributeError: 'TestSuite' object has no attribute 'getIncludeList'
(Pdb) self
<__main__.TestSuite object at 0x7f3cef7df890>
(Pdb) self.suite
*** AttributeError: 'TestSuite' object has no attribute 'suite'
(Pdb) up
> /home/tom/projects/test262/tools/packaging/test262.py(283)GetAdditionalIncludes()
-> return '\n'.join([self.suite.GetInclude(include) for include in self.GetIncludeList()])
(Pdb) self.GetIncludeList()
['propertyHelper.js\r']
(Pdb) self
<__main__.TestCase object at 0x7f3cee976210>
(Pdb) self.full_path
'/home/tom/projects/test262/test/built-ins/Math/acosh/acosh-descriptor.js'
(Pdb) 
`
`python tools/packaging/test262.py --command /home/tom/projects/mozilla-inbound/js/src/debug-obj/dist/bin/js built-ins/Math/acosh/acosh-descriptor`
fails in the same way reproducible

**Comment by evilpie** [comment] 2015-06-09 22:03
Oh, I think I figured it out. The trailing `\r` is probably the issue here.

**Comment by bterlson** [comment] 2015-06-09 22:30
LMK if that's for sure the case and I can close this (or you can!)

**Comment by evilpie** [comment] 2015-06-09 22:49
We still need to fix this. either by stripping the character or normalizing
all line endings to `\n`.

**Comment by anba** [comment] 2015-06-10 13:10
I was able to reproduce the failure when I explicitly loaded monkeyYaml. The following patch should be sufficient to fix this issue. Pinging @smikes for input.

```diff
diff --git a/tools/packaging/monkeyYaml.py b/tools/packaging/monkeyYaml.py
index 8ce33f7..85e1ae1 100644
--- a/tools/packaging/monkeyYaml.py
+++ b/tools/packaging/monkeyYaml.py
@@ -16,7 +16,7 @@ mYamlMultilineList = re.compile(r"^ *- (.*)$")
 def load(str):
     dict = None
 
-    lines = str.split("\n")
+    lines = str.splitlines()
     while lines:
         line = lines.pop(0)
         if myIsAllSpaces(line):
```

**Comment by evilpie** [comment] 2015-06-10 13:57
Yes this fixes it.

**Comment by arv** [comment] 2015-06-10 14:31
Uploading PR now

**Closed** 2015-06-11 16:06 UTC

**Comment by smikes** [comment] 2015-06-11 23:14
Thanks - looks good - I'm  a bit out of the loop this month.
