### ISSUE TITLE
Encoding Tests' Targeted Spec Version

### ISSUE THREAD

**Issue by jugglinmike** [tc39/test262#569] opened 2016-04-07 15:06 UTC
On gh-472 back in January, we discussed the potential difficulties with maintaining a test suite for a "living" specification--what, if anything, should Test262 do to account for the fact that specification revisions invalidate existing tests. At the time, consensus seemed to favor the simple-but-progressive solution: "delete the tests."

While I had some objections to that conversation's resolution, consensus seemed strong enough for me to let it go. [A recent inquiry](https://twitter.com/dshaw/status/717728678159855616) has prompted me to re-open the discussion as due dilligence to the project's current/potential consumers.

I have two use cases in mind:

First are implementors who are specifically targeting an older edition of the spec. While writing tests for ES2015, we sometimes find omissions in coverage for ES5 features. If TC-39's advice to these implementors is, ["use the tests at this tag,"](https://github.com/tc39/test262/pull/471#discussion_r50332324) it would be cutting them off from new tests written for older features (see, for example, gh-549 and gh-550). So this solution sends a clear signal that ECMA is not interested in the correctness of "legacy" runtimes.

Second, I can imagine that there are some projects which do not have the resources to track TC-39's new yearly release cycle. Or, even if they do, they may prefer to take a more conservative approach, waiting to commit to new features until formal ratification from ECMA. The practice of [deleting tests that are invalidated by the current draft](https://github.com/tc39/test262/issues/472#issuecomment-173006747) allows for inconsistency where it was previously forbidden. Even if you have no sympathy for so-called "legacy" runtimes, I think it is another matter to degrade the test suite's value for implementors honoring the latest publication.

To be honest, I don't have enough familiarity with the ecosystem of runtimes to say if either of those groups are large enough influence the decision here. But I suspect that they are the same people who would tend to be under-represented in TC-39 meetings. So although [Chakra, V8, and SpiderMonkey may be well-served by a "living test suite,"](https://github.com/tc39/test262/pull/471/files#r50334280) I don't want to take that as sufficient without considering these other (potential) interests. If you folks see potential in this line of reasoning, I would be willing to collect more conclusive data on implementors' preferences.

The label "living" is a bit misleading because it suggests any alternative would be slow, irrelevant, or otherwise "dead." I think we may be able to have our cake and eat it, too. My idea (as ever) revolves around more test metadata.

To keep `master` in a state that reflects the very latest draft but retains value for less progressive implementors, we would only need to author tests in a slightly different way:
- Include reference identifiers to the _first_ version that specified the
  behavior under test through a new tag named `introducedin` (e.g. `5`, `2015`,
  or even `harmony` for [tests of stage-3-and-above
  proposals](https://github.com/rwaldron/tc39-notes/blob/dd8bb263aef908509c91f58e4912482a75c1c74d/es7/2015-09/sept-24.md#8-test262-update))
- In cases where a later revision modified that behavior, include a new tag,
  `invalidatedby`, to describe the revision (this requires additional research,
  but the onus would be on the contributor, who would presumably already have
  knowledge about which edition revised the behavior they were testing)

That this would also resolve the current tension between "mainline" tests and those currently (and some would say, artificially) segregated in [the "annexB" sub-directory](https://github.com/tc39/test262/tree/c95e673febd2ad1252bee997106276602f60c580/test/annexB). Test262 could define a single canonical location for each language feature, and simply denote tests for Annex B functionality with, for example, `introducedin: es2015-annexb`.

The overhead to implementing this today is not too high, especially if research suggested that ES5 would be an acceptable baseline. It will become harder as time goes on and Test262 continues to accept more tests for features that span various editions and proposals.

Under this workflow, TC-39 could continue to accept tests even for ES3's restrictions on property names (for instance) at the same time (and on the same branch) as tests for async functions. Test262 would then be a comprehensive test suite for all ECMAScript, both "living" and "dead".

**Comment by leobalter** [comment] 2016-04-07 17:07
I have mixed opinions on this. 

I believe the motivation for this is caused by a major flaw on this project, which can be roughly defined as "we don't have proper coverage for ES6 yet".

In an ideal scenario, we should have ES7 released with full coverage, and that would be enough to use tags or maybe branches. That would be reasonable enough to say the tests on the master follow the current draft + stage 3 tests.

We are not close to that scenario: we are still running up to complete coverage for ES6 and we don't have a way to assure everything will be covered. We can - and should - eventually find missing points to write more tests.

What we have today and what we'll achieve with the tests for ES6 is a minimum desirable coverage. That means a tag or a branch won't be enough to capture the proper tests for the x or y edition. 

It's also not gonna be easy to maintain branches for these versions and than merge tests for each one of them. I can say that by the experience of jQuery maintaining versions 1.x and 2.x along.

The ideal scenario won't be achieved with the releases of ES2016 or ES2017, the coverage is cloudy over the specs text, building a tool to verify that seems costly and uncertain.

With that said, I believe this proposal might serve as a remedy. I would love to try and discuss more alternatives as I particularly don't like adding more metadata, but I don't have any better idea. Perhaps, bringing the kangax compatibility tests to become an official test262 project would be interesting, that should be done on another repo - like the parser tests - and demands the acceptance from Kangax, if that would add value to his project as well.

---

My other counterpoint using new metadata is that I believe they're not much used and most of the time ignored. 

I believe we should address other 2 milestones before: replace the current test-runner script with something that is not relying on deprecated technologies and allow optimizations + make the tests runnable anywhere through flags that can use the metadata. A good example would be allowing the tests to run on any browser and allow checkboxes to turn on and off features.

Those improvements would help us on a bigger challenge: having more people and implementors adopting test262. AFAIK, the only implementors currently using test262 are V8 (Google) and Chakra (Microsoft), it would be great to others as Spidermonkey (Mozilla) and JSC (Apple).

**Comment by allenwb** [comment] 2016-04-07 17:13
At any point in time there is only one official ECMA-262 standard.  When the Ecma General Assembly approves a new edition of ECMA-262 it complete supersedes all previous editions. ES1, ES3, and ES5.1 are no longer recognized "standards". They are just obsolete documents that are still available for historic reference. If an implementation is not trying to follow the current edition of ECMA-262 it is not trying to implement  "the ECMAScript Standard".  

There might be various reasons why some implementations might choose to freeze on an earlier edition of the ECMA-262 specification.  But if it does, it no longer (even aspirationally) an implementation of "the ECMAScript standard". It's not clear to me why TC39 would want to put energy into making life easier for such implementations,

**Comment by littledan** [comment] 2016-04-07 22:44
Supporting tests for ES2015 is a little bit of a funny proposition, as errata were not published for ES2015, with the fixes instead going into ES2016 and beyond. Most of the normative changes in ES2016 are fixes. @jugglinmike Do you have any users in mind who are targeting historical ECMAScript versions? If so, let's figure out what they are looking for, and work towards that. I like @leobalter 's solution of focusing on feature tags instead, though V8 does not use them currently.

@leobalter Minor: My understanding is that Mozilla and Apple are \[working on] using the current test262 tests as well.

**Comment by dshaw** [comment] 2016-04-08 03:57
@jugglinmike Thank you for inviting us into the process. As folks here may be aware, Node.js is a fairly new player to this largely browser-focused ecosystem.

Any metadata that test262 could provide would help Node.js effectively communicate to Node.js users which Ecmascript features are fully supported by the platform. Without it, we would have to curate an external mapping of what our understanding of the spec is. I'd much prefer to have those more intimately involved with this effort define the context needed to communicate these assertions.

**Comment by domenic** [comment] 2016-04-08 04:49
I think it's important that any such effort be focused on features, not on spec versions.

test262 might not be the best source of that information. Using test pass rate as a proxy for implementation status falls down in two ways:

1. When there is not 100% test coverage, you get no information about the feature's implementation status
1. When there are minor implementation bugs in edge cases---exactly the sort of thing test262 is meant to support---but the mainline usage scenarios that 99% of users will encounter are implemented correctly, you could get something like 5 passing tests out of 200, indicating that the feature is not implemented, when in fact it's just edge cases that have failed.

I'd instead suggest tracking the JavaScript category on https://www.chromestatus.com/features.

**Comment by littledan** [comment] 2016-04-08 20:53
@dshaw Is Node.js interested in testing for certain ECMAScript features and not others? If so, do these map well to test262's current feature tags, with Node.js wondering about certain subsets?

**Comment by jugglinmike** [comment] 2016-04-11 18:50
Thank you for your insight, @allenwb! This is exactly the kind of perspective I
lack, and it invalidates the first use case I proposed. (@littledan: I hadn't
gone so far as to find which runtimes aren't targeting ES2015, but it looks
like I won't have to.)

This says nothing about the second use case, though: implementors who are
tracking the latest edition and ignoring draft changes until ratification time.
At first glance, it seemed like this would align with @dshaw's interest in
effectively communicating platform capabilities. We *might* be able to address
this with boolean meta-data "flags"--`deprecated` and `unpublished`.

I say "might" because I don't know if that would actually help anyone. The
so-called "user-facing" VM's that I'm aware of all track progressive runtimes.
As long as SpiderMonkey (for instance) is progressively implementing the latest
working draft, Firefox will be forced to do the same. So while
"ES20XX-compliant" may be a useful marketing detail, it may not actually be a
target of any real-world implementation. (@domenic is no doubt shouting,
"finally!" right now.)

Thanks to all involved for the input. I'll follow up with a separate comment
with some ideas for @dshaw.

**Comment by jugglinmike** [comment] 2016-04-11 18:51
@dshaw: Test262's file structure is still improving, but we're moving towards
the following organization:

- `/built-ins/` - organized according to the structure of built-in (not just
  "global") objects
- `/language/` - organized according to feature's expression in the syntactic
  grammar where possible (this is a little hand-wavy because many details don't
  match up to explicit productions--module code evaluation, for instance)
- `/annexB/` - mimics the above structure

You can use the file structure to determine which tests are relevant for
Node.js. Beyond that, you can use the frontmatter to make finer-grained
distinctions. We try to use the `features` tag when a test requires using a
recently-introduced aspect of the language other than the one under test. Also,
tests for stage-3-and-above proposals will specify `esid: pending` until they
are included in a published version of the specification.

Finally, you will likely have to maintain a blacklist of file names for those
tests that Node's version of V8 is currently failing.

Does this seem feasible to you? Is there anything we could do differently to
make things easier?

**Comment by jugglinmike** [comment] 2016-04-11 22:33
On second thought, it's a little premature to close this issue. Between
responses from @domenic and @littledan, and a suggested workflow from myself,
we've given @dshaw a lot to think about. We should definitely get his input
before considering this resolved!

**Comment by bterlson** [comment] 2016-04-12 23:37
Overall I think there is definitely some things that we can do to improve Test262's usefulness for people that are not engine implementers. I would support maintaining additional flags that would help ES engine consumers communicate with their developers what level of ES support they are claiming. But I would like to hear more about @dshaw's goals before committing to a particular path forward.

I think part of the complexity here is determining a baseline. Feautre-by-feature works great for our new features but there is thousands of tests that are just how JS works and these tests are spread throughout the repository. To @allenwb's points, I agree it should be a non-goal to test ES5-level conformance as ES5 was ratified, but it seems reasonable to run tests that should pass both in an ES5-compliant implementation as well as an implementation conforming to the latest ratified standard. Running tests that contain es5id/es6id is an approximation that may serve but perhaps something more rigorous is called for.

**Comment by jugglinmike** [comment] 2016-04-18 15:29
> Running tests that contain es5id/es6id is an approximation that may serve but
> perhaps something more rigorous is called for.

I think this approach may be sufficient in the short-term, but it's not
something we can endorse for long:

- Because we don't intend to support `es7id`, we won't be able to make similar
  distinctions about (for instance) the exponentiation operator once the 2016
  draft is ratified. Not to mention the many small changes that have been made
  outside of the formal proposal process.
- It's cumbersome (and largely redundant) for tests for ES6-and-beyond. The
  numeric section ID is being subsumed by the contextual `esid`, so finding and
  encoding this value is kind of a hassle.

If we intend to support this use case moving forward, then we should commit to
a pattern that is easy to explain (e.g. *not* "please add an irrelevant section
number if your test concerns ES6), works for future editions, and avoids
unnecessary overhead.

So maybe the `indroducedin` tag has value, after all? Because of those small
spec changes, this will require some taxonomy work today (in other words, not a
simple find-and-replace), but that task will only get harder with time.

**Comment by leobalter** [comment] 2016-04-18 15:52
The `introducedin` tag seems good and adds useful information that can be used to filter features that are not yet a standard (draft + stage 3+), as an example. It does not enforce anyone to avoid any test and can be used to define priorities to implement.

Can we have an issue to discuss the values that should be used?

PS: s/indroducedin/introducedin

**Comment by domenic** [comment] 2016-04-18 15:58
I think we should wait for implementer or consumer interest before anyone considers spending valuable time on such discussions, much less work.

**Comment by leobalter** [comment] 2016-04-18 17:29
@jugglinmike and I are consumers of this project as we maintain in and actively write new tests.

The proposed feature doesn't need to be consumed by anyone, it's just a flag that can be ignored at anytime. Plus, it may be helpful as an extra informative tag, like `info`. Implementing it won't cause much extra work.

Reviewing it again, this tag is interesting to quickly track new features to test, instead of repeating long runs for the tests.

**Comment by domenic** [comment] 2016-04-18 17:30
How would this flag help you maintain and actively write new tests?

**Comment by leobalter** [comment] 2016-04-18 17:51
If you want an example, we current have tests on PRs where I'm not sure when it was updated. That helps me reviewing and checking each of the changed parts on the spec. Looking at the changes it also helps me to tell if we are missing any other change on the tests, as missing tests or other tests that should be removed.

**Comment by bterlson** [comment] 2016-04-18 20:28
introducedin seems fine to me too, but we should not do anything until we get an idea of if it would help @dshaw's Node scenarios. Seems like it would - if we had this metadata on all tests, we could get es5 baseline with an introducedin of es5.

I could bikeshed the name though - if the intention is to have a standard version number here, maybe something like `spec` would be sufficient?

**Comment by ljharb** [comment] 2016-06-10 22:00
I was asked to add my use case here - for the es5-shim (especially if there's interest in migrating my tests into test262) I need a way to run *es5 tests only* against an engine. Similarly, es6-shim needs a way to run *es5 and es6 tests only* against an engine.

Currently I'm jumping through hoops with `grep`/`ag`, and running into "arguments list too long" errors from an engine, trying to run only ES5 tests - why is this contentious?

**Comment by ljharb** [comment] 2016-06-10 22:04
My other question is, if I can't trivially filter by all the things in the frontmatter, why are we all wasting our time typing out the useless things in the frontmatter?

**Comment by littledan** [comment] 2016-06-10 22:51
To have good conformance tests for ES5, we'd want things which are actually invalid in ES2015. Browsers today are moving to support more recent ES draft spec texts, *rather than* not *in addition to* previous versions.

I definitely support some sort of frontmatter representation of things that are not yet at Stage 4 so that engines which try to conform to the full draft spec can exclude them. For more data beyond that, I don't have any particular objection to adding an introducedin tag; though I don't see how it would be especially useful for browsers, but those are just one user of test262. For @dshaw 's use case, introducedin es5 may be a lower bar than you might want--Node 6 users can count on V8 supporting most ES2015 features, and even Node 4 users get some. I could see it being useful for @ljharb .  Any other use cases?

**Comment by ljharb** [comment] 2016-06-10 23:39
fwiw, I'd love if ES5 tests that became invalid in ES6 (like, say, `Object.keys(null)` throwing) were preserved, but with frontmatter identifying them as such.

**Comment by leobalter** [comment] 2017-03-13 20:52
as far as I remember, this topic has also been discussed in some meetings. Test262 is covering the living current specs up to draft and stage 3 proposals.

**Comment by leobalter** [comment] 2020-07-14 01:23
Since this bug was opened we've worked on an universal identifier (esid) and better handlings for feature identifiers, rather than release editions. Even test262.report makes a good usage of it. 

I don't think we're currently targeting something else for this but I'd suggest opening a new issue for anything we propose.

**Closed by leobalter** 2020-07-14 01:23 UTC
